FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && \
    apt-get install -y ffmpeg libgl1 libsm6 libxext6 && \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "drowsiness:app", "--bind", "0.0.0.0:8000", "--workers", "1", "--timeout", "120"]